name: Customize Raspberry Pi OS image
'on':
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_release:
    name: Build and release custom image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install editorconfig-checker
          sudo ln --symbolic "$(which editorconfig-checker)" /usr/local/bin/ec
          sudo snap install --channel=edge shellcheck

      - name: Build custom image
        run: |
          make version
          make lint
          make build

      - name: Set environment variables
        run: |
          echo "FILENAME_ARCHIVE=$(ls *-custom.tar.bz2)" >> $GITHUB_ENV
          echo "FILENAME_SHA256=$(ls *-custom.tar.bz2.sha256)" >> $GITHUB_ENV

      - uses: dev-drprasad/delete-older-releases@v0.1.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest Release
          commitish: master
          draft: false

      - name: Upload custom image
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.FILENAME_ARCHIVE }}
          asset_name: ${{ env.FILENAME_ARCHIVE }}
          asset_content_type: application/x-bzip2

      - name: Upload custom image checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.FILENAME_SHA256 }}
          asset_name: ${{ env.FILENAME_SHA256 }}
          asset_content_type: text/plain
